name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-26, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - run: cmake -S . -B build -DCMAKE_CXX_STANDARD=20
      - run: cmake --build build
      - if: ${{ runner.os == 'Windows' }}
        run: cp build/Debug/test.exe build
      - run: build/test

      - run: cmake -S . -B build -DCMAKE_CXX_STANDARD=23
      - run: cmake --build build
      - if: ${{ runner.os == 'Windows' }}
        run: cp build/Debug/test.exe build
      - run: build/test

      - if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
          valgrind --leak-check=yes --error-exitcode=1 build/test

      - if: ${{ runner.os == 'macOS' }}
        run: /opt/homebrew/opt/llvm@20/bin/scan-build --status-bugs cmake --build build --clean-first

      - run: cmake -S . -B build
      - run: cmake --build build
      - run: cmake --install build --prefix /tmp
      - run: g++ -std=c++20 -I/tmp/include -o example/main example/main.cpp
